from marshmallow import fields
from schemas import ma

# Define the customer 
class CustomerSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True)
    email = fields.String(required=True)
    phone = fields.String(required=True)
    username = fields.String(required=True)
    password = fields.String(required=True)

class CustomerUpdateSchema(ma.Schema):
    name = fields.String(required=False)
    email = fields.String(required=False)
    phone = fields.String(required=False)
    username = fields.String(required=False)
    password = fields.String(required=False)

# Create instances of the schema
customer_input_schema = CustomerSchema()
customer_output_schema = CustomerSchema(exclude=["password"])
customers_schema = CustomerSchema(many=True, exclude=["password"])
customer_login_schema = CustomerSchema(only=["username", "password"])
customer_update_schema = CustomerUpdateSchema()