from marshmallow import fields
from schemas import ma

# Define the order 
class OrderSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    customer_id = fields.Integer(required=True)
    products = fields.Nested("ProductIdSchema", required=True, many=True)

# Create instances of the schema
order_schema = OrderSchema()
orders_schema = OrderSchema(many=True)