from marshmallow import fields, validate
from schemas import ma

# Define the product 
class ProductSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True)
    price = fields.Float(required=True, validate=validate.Range(min=0))
    stock_quantity = fields.Integer(required=True, validate=validate.Range(min=0))

class ProductIdSchema(ma.Schema):
    id = fields.Integer(required=True)

class ProductUpdateSchema(ma.Schema):
    name = fields.String(required=False)
    price = fields.Float(required=False, validate=validate.Range(min=0))
    stock_quantity = fields.Integer(required=False, validate=validate.Range(min=0))

# Create instances of the schema
product_schema = ProductSchema()
products_schema = ProductSchema(many=True)
product_update_schema = ProductUpdateSchema()